AcidLabs/AcidLabsFrontEnd/Controllers/IndicatorsController.cs
using AcidLabsFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AcidLabsFrontEnd.Controllers
{
    public class IndicatorsController : Controller
    {
        // GET: Indicators
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Método que retorna listado de objetos JSON
        /// </summary>
        /// <returns>Listado de objetos "Countries"</returns>
        public JsonResult GetCountries()
        {
            WebClient client = new WebClient();
            string uriApi = "http://acidlabsapiservices.azurewebsites.net/api/GetCountries";
            string jsonCountries = client.DownloadString(uriApi);

            List<Countries> countriesList = new List<Countries>();
            countriesList = JsonConvert.DeserializeObject<List<Countries>>(jsonCountries);

            return Json(countriesList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método utilizado para la validación de datos
        /// </summary>
        /// <param name="country">País</param>
        /// <param name="startYear">Año inicio</param>
        /// <param name="endYear">Año fin</param>
        /// <returns>Objeto JSON</returns>
        [HttpPost]
        public ActionResult Validacion(string country, string startYear, string endYear)
        {
            try
            {
                return Json(new
                {
                    correcto = true,
                    url = Url.Action("VisualizarIndicadores", new { country, startYear, endYear })
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    correcto = true,
                    mensaje = ex.Message
                });
            }   
        }

        /// <summary>
        /// Método que devuelve una vista, para visualización de indicadores
        /// </summary>
        /// <param name="country">País</param>
        /// <param name="startYear">Año inicio</param>
        /// <param name="endYear">Año fin</param>
        /// <returns>Vista</returns>
        public ActionResult VisualizarIndicadores(string country, string startYear, string endYear)
        {
            ViewBag.country = country;
            ViewBag.startYear = startYear;
            ViewBag.endYear = endYear;
            return View();
        }

        /// <summary>
        /// Método "Server-Side" que retorna listado de objetos JSON para indicadores de natalidad y mortalidad
        /// </summary>
        /// <param name="param">Objeto parámetros jqueryDataTable</param>
        /// <param name="country">País</param>
        /// <param name="startYear">Año inicio</param>
        /// <param name="endYear">Año fin</param>
        /// <returns>Listado de objetos JSON</returns>
        public JsonResult GetDataIndicatorsServer(jQueryDataTableParams param, string country, string startYear, string endYear)
        {
            // Obteniendo registros
            WebClient client = new WebClient();
            string uriApi = string.Format("http://acidlabsapiservices.azurewebsites.net/api/GetIndicators/{0}/{1}/{2}", country, startYear.Trim(), endYear.Trim());
            string jsonIndicators = client.DownloadString(uriApi);
            var indicatorsList = JsonConvert.DeserializeObject<List<Indicators>>(jsonIndicators);
            IQueryable<Indicators> memberCol = indicatorsList.AsQueryable();

            // Filtros
            int totalCount = memberCol.Count();
            IEnumerable<Indicators> filteredMembers = memberCol;
            if (!string.IsNullOrEmpty(param.sSearch))
            {
                filteredMembers = memberCol
                        .Where(m => m.CountryName.Contains(param.sSearch) ||
                                    m.Year.Contains(param.sSearch) ||
                                    m.BirthRateCrude.Contains(param.sSearch) ||
                                    m.MortalityRateAdultFemale.Contains(param.sSearch) ||
                                    m.MortalityRateAdultMale.Contains(param.sSearch) ||
                                    m.MortalityRateInfant.Contains(param.sSearch) ||
                                    m.MortalityRateUnder5.Contains(param.sSearch) ||
                                    m.MortalityRate.Contains(param.sSearch));
            }

            // Orden
            var sortIdx = Convert.ToInt32(Request["iSortCol_0"]);
            Func<Indicators, string> orderingFunction =
                                (
                                m => sortIdx == 0 ? m.CountryName :
                                     sortIdx == 1 ? m.Year :
                                     sortIdx == 2 ? m.BirthRateCrude :
                                     sortIdx == 3 ? m.MortalityRateAdultFemale :
                                     sortIdx == 4 ? m.MortalityRateAdultMale :
                                     sortIdx == 5 ? m.MortalityRateInfant :
                                     sortIdx == 6 ? m.MortalityRateUnder5 :
                                  m.MortalityRate
                                 );
            var sortDirection = Request["sSortDir_0"]; // asc or desc  
            if (sortDirection == "asc")
                filteredMembers = filteredMembers.OrderBy(orderingFunction);
            else
                filteredMembers = filteredMembers.OrderByDescending(orderingFunction);
            var displayedMembers = filteredMembers
                     .Skip(param.iDisplayStart)
                     .Take(param.iDisplayLength);

            // Resultados
            var result = from a in displayedMembers
                         select new
                         {
                             a.CountryName,
                             a.Year,
                             a.BirthRateCrude,
                             a.MortalityRateAdultFemale,
                             a.MortalityRateAdultMale,
                             a.MortalityRateInfant,
                             a.MortalityRateUnder5,
                             a.MortalityRate
                         };

            // Retornando resultados JSON
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = totalCount,
                iTotalDisplayRecords = filteredMembers.Count(),
                aaData = result
            },JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método "Client-Side" que retorna listado de objetos JSON para indicadores de natalidad y mortalidad
        /// </summary>
        /// <param name="param">Objeto parámetros jqueryDataTable</param>
        /// <param name="country">País</param>
        /// <param name="startYear">Año inicio</param>
        /// <param name="endYear">Año fin</param>
        /// <returns>Listado de objetos JSON</returns>
        public ActionResult GetDataIndicatorsClient(jQueryDataTableParams param, string country, string startYear, string endYear)
        {
            // Obteniendo registros
            WebClient client = new WebClient();
            string uriApi = string.Format("http://acidlabsapiservices.azurewebsites.net/api/GetIndicators/{0}/{1}/{2}", country, startYear.Trim(), endYear.Trim());
            string jsonIndicators = client.DownloadString(uriApi);
            var indicatorsList = JsonConvert.DeserializeObject<List<Indicators>>(jsonIndicators);

            // Retornando resultados JSON
            var jsonResult = Json(new { aaData = indicatorsList }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }
    }
}

AcidLabs/AcidLabsFrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AcidLabs</title>
    <link rel='icon' href="@Url.Content("~/favicon.ico")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'e58e7658-0ef4-44c8-bc8c-441c7ced446a'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AcidLabs", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Indicadores", "Index", "Indicators")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="divLoading" class="loading" style="visibility:hidden;z-index:2000;">
            <div id="loading-animation"></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ricardo Montecino</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>